### ISSUE TITLE
[BUG]: Demo Site > Contributor Section not displaying all users from git-in-here.yml

### ISSUE THREAD

**Issue by kiddjsh** [Lissy93/git-into-open-source#127]
### Component

lib - Scripts used to generate content

### Please describe the issue

At Demo Site https://git-into-open-source.as93.net/ > Contributors Section, the below list of contributors are not actively displaying on the website that are actively present in the git-in-here.yml; Some existing contributor image icons are not properly displaying as well.

- username: anshika-verma05
  question: *Q1
  response: >-  
    Getting into the open source is an amazing opportunity to expand our skills,work on real-world
    projects and connect with the community of passionate individuals.It's a great chance to make a 
    positive impact on the world-all while learning from experienced developers.

- username: entrerbrianup 
  question: *Q1
  response: >- 
    I want to get into open source to learn, contribute, and collaborate with others in the community
    and get good connection in the field of Computer science world.
    
- username: GettingWeirdKnowledge
  question: *Q1
  response: >-
     I've always been fond of the way open-source indicates the strength of the masses.
     Making contributions together not only helps numerous people develop their skills but also ends up 
     creating a beautiful end product and providing a sense of community and togetherness to programming. 
     I couldn't manage to find time earlier but now that I have some,
     I'm excited and eager to play my part in providing contributions and sharing my knowledge.

- username: haxybaxy
  question: *Q3
  response: >-
     My advice for someone who wants to get into open source is to JUST START. Even if you don't know anything about anything, learning will be 
     so much easier when you are doing hands on work. We often think that acquiring new skills or learning something new is going to take us a lot
     of time, which discourages us, but the thing is that timewill pass anyways. Keep at it and you will achieve something great!

- username: kiddjsh
  question: *Q1
  response: >-
    Open Source Projects will allow me to get involved within different communities 
    giving me an opportunity to further develop skills, by contributing to source
    code in areas of development, documentation, bug fixes, and testing, that will 
    be recognized by community members and hiring managers, which will help in 
    advancing my software development career.

- username: YashkShrivas4491
  question: *Q3
  response: >-
     Hey Folks 👋🏻💻, if don't know about open-source and how to contribute,
     don't worry you will get there just by learning,
     doing hands-on practice and sharing knowledge with others,
     I also want to say that learning in public plays a very significant
     role because it can create lots of opportunities for you.

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Heya @kiddjsh 
Thanks for this, could you send a screenshot for what you're seeing, as for me I can see those contributors
It could just be that the website takes a few mins to update after a PR is merged.

<details>

![image](https://github.com/Lissy93/git-into-open-source/assets/1862727/abdd7aad-d406-4909-88fc-59d5b274cb89)
</details>

**Comment by kiddjsh** [comment]
Hey @Lissy93 , I do apologize, it appears that the Demo https://git-into-open-source.as93.net/ must have been out of sync. As you said in your comment above the user image for @enterbrianup is not displaying due to a typo. Though, since I have this ticket open, I thought I'd ask as well with the README and Mirror Site. In the README.md in this repo, it's not displaying all Contributors in the bottom section, is there a separate exercise for this, or should all Contributors in the git-in-here.yml being displaying in the bottom section as well, see snippet contributorsREADME BOTTOM? Also, the mirror site at https://codeberg.org/alicia/git-into-open-source is not up to date, or in sync with changes in GitHub, since it's referenced should it also be updating at the same time the GitHub repo is syncing, see snippet mirrorCodeBerg? If these are separate issues you would like opened after your review, I can create new tickets. Thanks!
![contributorsREADME BOTTOM](https://github.com/Lissy93/git-into-open-source/assets/70739345/82de58aa-3452-4218-a12d-a8529f99237e)
![mirrorCodeBerg](https://github.com/Lissy93/git-into-open-source/assets/70739345/50b7819a-0383-4248-abf8-b34bc1289654)

**Comment by Lissy93** [comment]
Yeah, you're right - reason being is that they're triggered by a cron job using GitHub actions (here's the workflow file for [mirroring](https://github.com/Lissy93/git-into-open-source/blob/main/.github/workflows/mirror.yml), and here's the one for [inserting contributors](https://github.com/Lissy93/git-into-open-source/blob/main/.github/workflows/insert-credits.yml)).
So at the moment, the website and git-in-here list are updated shortly after any change is made, but the other jobs only happen weekly. We could update this so they run more often or whenever a certain file is updated, but I originally put it as weekly just so that it would cost less in compute.

**Comment by kiddjsh** [comment]
Since it's run on a weekly basis, I think it would be a good idea to have the instructions updated to notate the weekly cron job process, so that contributors are not confused as to why the site isn't immediately updating. Most people would probably think they have completed a task incorrectly, if it's not immediately seen. 

If you approve, I can make an update to any files, i.e. README.md, Submit your first PR (Terminal), Submit your first PR (CLI), etc. and any other templates needed...to include some kind of celebration statement of understanding that a contribution has been made but the site won't update until the weekly cron job process completes its cycle. Would need a complete list of designated files to have updated, and I could come up with some verbiage to have approved, whacha think?
