### ISSUE TITLE
[QUESTION]: This repository has been excluded from Hacktoberfest 2023.

### ISSUE THREAD

**Issue by Addyk16** [Lissy93/git-into-open-source#133]
### Question

[QUESTION]: This repository has been excluded from Hacktoberfest 2023.
I got to know about this repo from an issue on another past hacktoberfest repo. That issue claimed that this repo is for hacktoberfest 2023. Please either fix this or stop making false claims. 

![image](https://github.com/Lissy93/git-into-open-source/assets/72308974/27779956-9a42-45a9-8d7a-084631e4e89f)

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow the [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
I'll reach out to them :)
Yeah, there's been so much spam this year, so I think it's great that they're taking excluding more seriously this time round

**Comment by Lissy93** [comment]
Oh PRs which don't meet the requirements from the contributing guidelines will be automatically excluded, but you should see what you need to change in a comment in your PR. Again, just to prevent spam and low effort contributions.
