### ISSUE TITLE
[FEATURE]: Alignment of UI structure

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Lissy93/git-into-open-source#136]
### Feature Suggestion

First of all, your project is amazing and I am really impressed with the idea. The feature or you can say a styling that I want to improve is that some of the things are unstructured for mobile and desktop screen sizes.

## Screenshots
![image](https://github.com/Lissy93/git-into-open-source/assets/55249639/7a7daf06-d0e0-469e-bba9-1e8ad2b95c65)
As you can see, the font sizes doesn't fit well for small screens

![image](https://github.com/Lissy93/git-into-open-source/assets/55249639/5d5acf8b-2c36-4099-8401-e6e5d3d34151)
On the guides page, the heading is left aligned and out of the place, I think it looks good at the center, also there is no spacing between the content and heading.

![image](https://github.com/Lissy93/git-into-open-source/assets/55249639/02c6aa8d-1e27-4623-b76a-c18f88e23d99)
In the contributors' section, there isn't much spacing. 

### Would you be up for working on this?

Hell yeah!

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by theWiseAman** [comment]
@Lissy93 Can you assign this issue to me? I have experience with frontend web development and I am looking for an good pr merge during hacktoberfest.

**Comment by KSSaiTeja** [comment]
@Lissy93 please assign this issue to me.  i have prior knowledge. if i am given an oppurtunity i will be more happy to serve this repository
