### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by sanchitaa14** [Lissy93/git-into-open-source#15]
### Feature Suggestion

Adding my own experience as someone new to tech and exploring the world of opensource into the site

### Would you be up for working on this?

Hell yeah!

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Lissy93** [comment]
Heya @sanchitaa14 

Not certain what your asking here, but do you mean how to add your experience to the README?

If so, you just need to edit the [git-in-here.yml](https://github.com/Lissy93/git-into-open-source/blob/main/git-in-here.yml) file, and following the instructions in [CONTRIBUTING.md](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CONTRIBUTING.md) to submit a PR.

**Comment by Lissy93** [comment]
Closing as merged in #16
