### ISSUE TITLE
[BUG]: The text alingment is not good

### ISSUE THREAD

**Issue by narasimha-1511** [Lissy93/git-into-open-source#21]
### Component

lib - Scripts used to generate content

### Please describe the issue

![image](https://github.com/Lissy93/git-into-open-source/assets/129654598/643fa18b-01a2-4329-a73c-9eb4b32a71e2)
checkout the names of contributors not even alingned correctly 

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [x] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by Avinesh2** [comment]
can you assign me this issue ?

**Comment by Rohankr18** [comment]
I want to contribute.

**Comment by Mohit-0918** [comment]
hi @Lissy93 would you please assign this to me for the hackotoberfest.

**Comment by Mohit-0918** [comment]
hey @Lissy93 would you please assign this to me.

**Comment by inbuilt-aura** [comment]
@Lissy93,is this issue open.Can i contribute?

**Comment by spirit-124** [comment]
Hey @Lissy93  I would love to contribute to this issue can you please assign me this issue.

**Comment by TechoChat** [comment]
@Lissy93 is this issue still open ? can I contribute here ?

**Comment by Lissy93** [comment]
Fixed in 6f8fa90d2e19e924353ce1bf8c7fe1ba974e60ee
Was casused by some nasty tailwind classes
