### ISSUE TITLE
[FEATURE]: "Contributors" change into Middle of the Website

### ISSUE THREAD

**Issue by soura07** [Lissy93/git-into-open-source#40]
### Feature Suggestion

The GitHub issue titled "If the Contributor div into the middle of the website is better showing in this website" addresses a common concern in web development and design.

On the positive side, a central location can draw more attention to the contributors, emphasizing their importance. It can also create a balanced visual layout, enhancing the overall user experience

![image](https://github.com/Lissy93/git-into-open-source/assets/116977697/e0c0d570-4e58-463e-ba72-6df08fd9e6cb)

### Would you be up for working on this?

Yes, but with support

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by sumitj3na69** [comment]
Assign me this issue.

**Comment by TechoChat** [comment]
Assign me te issue I would love to contribute and help you out

**Comment by fatimashaikh04** [comment]
Assign this issue to me

**Comment by soura07** [comment]
@Lissy93 Assign me to solve this problem

**Comment by Lissy93** [comment]
Happy for any of you to pick this up, just let us know here who is going to submit the PR.
And feel free to ask if you have any questions about how to implement this :)

**Comment by priyanshusharma80** [comment]
Hi @Lissy93 Would you plz assign this issue to me, This is my first time in open source contribution & I want you to help me making my first ever contribution in open source :)

Thanks, Waiting For your Response :)

**Comment by aditya4567uk** [comment]
you'll be seeing PR shortly :) , I am Working on it

**Comment by aditya4567uk** [comment]
@Lissy93 my work has been done , i have centered "CONTRIBUTION" , "GUIDE", "EXTERNAL RESOURCES".
couls you assign me then i can merge the code via PR

**Comment by anshul-132002** [comment]
@Lissy93 Assign me to solve this problem
