### ISSUE TITLE
[FEATURE]:  If click this "Let's go" button in default mode not in dark mode the "Let's go" is not visible.

### ISSUE THREAD

**Issue by soura07** [Lissy93/git-into-open-source#41]
### Feature Suggestion

If click this "Let's go" button in default mode not in dark mode the "Let's go" is not visible. If I change to white color and any visible color in default mode it shows better than the previous design.

![image](https://github.com/Lissy93/git-into-open-source/assets/116977697/e9889e00-7893-4b47-86c2-5802dfd252a5)

### Would you be up for working on this?

None

### Pre-Submission Checklist

- [X] I have checked this issue has [not already been raised](https://github.com/Lissy93/git-into-open-source/issues?q=is%3Aissue)
- [X] I've searched the [docs](https://github.com/Lissy93/git-into-open-source/tree/main/.github) for an answer
- [X] I agree to follow thr [Code of Conduct](https://github.com/Lissy93/git-into-open-source/blob/main/.github/CODE_OF_CONDUCT.md)

**Comment by vishesh-hue** [comment]
yes i got the jest for it and i can contribute it

**Comment by Avineesh28** [comment]
Heyy there!
How do contributions work in this repository?
Am I assigned the job and then start working on it or do I just raise a merge request?
Either way I have the solution ready, please do let me know whichever

**Comment by AlefiyaAbbas** [comment]
I faced a similar problem during mu project. Please assign this issue to me

**Comment by Lissy93** [comment]
Heya @Avineesh28 
If you've got the solution, would you be able to submit a PR and I'll review it :)
Lemme know if you need any help

**Comment by Avineesh28** [comment]
Sure thing!
 You'll be seeing a PR shortly!

**Comment by soura07** [comment]
@Lissy93 Assign me : )

**Comment by Avineesh28** [comment]
Hey @Lissy93 !
While trying to implement the solution in my fork and seeing if it works I came across a bug in the project that inhibits the functionality and might just be causing the problem in the first plac. I've raised an issue regarding the same and put all the information I had on it in the issue. I'll continue to work on both of this until I find a solution

**Comment by shivamk23** [comment]
let me do this.
